---
environment:

  matrix:
    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  # We need tox installed for the tests
  - "%PYTHON%\\Scripts\\pip.exe install -U tox wheel setuptools"

build_script:
  - "if %appveyor_repo_tag% (%PYTHON%\\python.exe setup.py release sdist bdist_wheel) else (%PYTHON%\\python.exe setup.py sdist bdist_wheel)"

test_script:
  - "%PYTHON%\\Scripts\\tox.exe -e py"

artifacts:
  - path: 'dist/mycmath-*.whl'
  - path: 'dist/mycmath-*.zip'

deploy:
  provider: GitHub
  description: release $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: VzO72c+6RPmLxtoJjQ10IsDAEoWa3kTDky9cpO+XaoZN3BXybFA6sbscOsYJkIKJ
  artifact: /mycmath-.*\.(whl|zip)/
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true
